Fixups for parsers:
csv.reader is unicode now

Traceback (most recent call last):
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\balt.py", line 1771, in __Execute
    self.Execute()
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\basher\mod_links.py", line 2285, in Execute
    editorIds.readFromText(textPath)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 111, in readFromText
    with _CsvReader(csv_path) as ins:
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\bash\parsers.py", line 63, in __init__
    delimiter = b';' if b';' in first_line else b','
TypeError: 'in <string>' requires string as left operand, not bytes